[versions]
assertj = "3.26.3"
ini4j = "0.5.4"
intellij-platform = "2.10.2"
json = "20250517"
junit = "5.13.4"
kotlin = "2.2.0"
kotlinx-coroutines = "1.10.2"
luaj = "3.0.1"
mockk = "1.14.5"
okhttp = "5.1.0"
spotless = "8.1.0"

[libraries]
assertj = { group = "org.assertj", name = "assertj-core", version.ref = "assertj" }
ini4j = { group = "org.ini4j", name = "ini4j", version.ref = "ini4j" }
json = { group = "org.json", name = "json", version.ref = "json" }
junit-jupiter-api = { group = "org.junit.jupiter", name = "junit-jupiter-api", version.ref = "junit" }
junit-jupiter-engine = { group = "org.junit.jupiter", name = "junit-jupiter-engine", version.ref = "junit" }
junit-jupiter-params = { group = "org.junit.jupiter", name = "junit-jupiter-params", version.ref = "junit" }
junit-vintage-engine = { group = "org.junit.vintage", name = "junit-vintage-engine", version.ref = "junit" }
kotlin-test = { group = "org.jetbrains.kotlin", name = "kotlin-test", version.ref = "kotlin" }
kotlinx-coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "kotlinx-coroutines" }
luaj = { group = "org.luaj", name = "luaj-jse", version.ref = "luaj" }
mockk = { group = "io.mockk", name = "mockk", version.ref = "mockk" }
okhttp = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okhttp" }
okhttp-mockwebserver = { group = "com.squareup.okhttp3", name = "mockwebserver", version.ref = "okhttp" }

[plugins]
intellij-platform = { id = "org.jetbrains.intellij.platform", version.ref = "intellij-platform" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
